Guests = ["Irene Rex", "Lucy Rex", "Eunice Rex"]
 Guests.insert(0, "Michelle Obama")
 Guests.insert(2, "Clark Peoples")
 Guests.append( "Ayo Edebiri")
 Guests.sort()
 print("\nUpdated Guest List (Sorted):")
 print(Guests)
 print("\nDinner Invitations :")
 print(f"Dear Michelle Obama, I would love to have you join me for dinner.")
 print(f"Dear Irene Rex, I would love to have you over for dinner.")
 print(f"Clark Peoples, I would love to have you join me for dinner.")
 print(f"Dear Lucy Rex, I would love to have you join me for dinner. ")
 print(f"Dear Eunice Rex, I would love to invite you over for dinner")
 print(f"Dear Ayo Edebiri, I would love to have you join me for dinner.")
 print("The first three items in the list are:")
 print(Guests[:3])
 print("\nThree items from the middle of the list are:")
 middle_index = len(Guests) // 2
 print(Guests[middle_index - 1: middle_index + 2])
 print("\nThe last three items in the list are:")
 print(Guests[-3:])